# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/warrensbox/terraform-switcher

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: mkdir -p build
      - run: go build -v -o build/tfswitch

      - persist_to_workspace:
          root: build
          paths: tfswitch

  test:
    docker:
      - image: "circleci/ruby:2.5-stretch"

    steps:
      - run: ls

      - attach_workspace:
          at: build

  develop-master:
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run: 
          command: |
            git status
            source version 
            export RELEASE_VERSION
            git tag $RELEASE_VERSION.${CIRCLE_BUILD_NUM}
            git config --global user.email "warren.veerasingam@gmail.com"
            git config --global user.name "warrensbox"
            git push origin $RELEASE_VERSION.${CIRCLE_BUILD_NUM}

  release:
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run: 
          command: |
            set +e
            source version
            export RELEASE_VERSION; 
            RELEASE_VERSION=$RELEASE_VERSION.${CIRCLE_BUILD_NUM}
            export RELEASE_VERSION;
            echo $RELEASE_VERSION
            go get -v -t -d ./...
            git config user.email "warren.veerasingam@gmail.com"
            git config user.name "warrensbox"
            git tag -a ${RELEASE_VERSION} -m "Release Version"
            git push origin ${RELEASE_VERSION}
            curl -L https://git.io/goreleaser | VERSION=v0.76.1 bash

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - develop-master:
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - develop-master
          filters:
            branches:
              only: 
              - release
              - master

