# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/warren-veerasingam/terraform-switcher

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: mkdir -p build
      - run: go build -v -o build/tfswitch

      - persist_to_workspace:
          root: build
          paths: tfswitch

  test:
    docker:
      - image: "circleci/ruby:2.5-stretch"

    steps:
      - checkout

      - attach_workspace:
          at: build

  deployment:
    docker:
      # specify the version
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run: ls
      - run: git status
      - run: git push --set-upstream origin 0.0.${CIRCLE_BUILD_NUM}



workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - test
          filters:
            branches:
              only: master
