# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/warrensbox/terraform-switcher

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: mkdir -p build
      - run: go build -v -o build/tfswitch

      - persist_to_workspace:
          root: build
          paths: tfswitch

  test:
    docker:
      - image: "circleci/ruby:2.5-stretch"

    steps:
      - run: ls

      - attach_workspace:
          at: build

  release:
    docker:
      - image: circleci/golang:1.10
    branches:
      only:
        - master

    steps:
      - checkout
      - run: ls
      - run: git status
      - run: source version; export VERSION; git tag ${VERSION}.${CIRCLE_BUILD_NUM}
      - run: git config --global user.email "warren.veerasingam@gmail.com"
      - run: git config --global user.name "warrensbox"
      - run: git push origin 0.0.${CIRCLE_BUILD_NUM}

  deployment:
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run: 
          command: |
            set +e
            source version
            export VERSION; 
            VERSION=$VERSION.${CIRCLE_BUILD_NUM}
            export VERSION;
            echo $VERSION
            go get -v -t -d ./...
            git config user.email "warren.veerasingam@gmail.com"
            git config user.name "warrensbox"
            git tag -a ${VERSION} -m "Release"
            git push origin ${VERSION}
            curl -L https://git.io/goreleaser | VERSION=${VERSION} bash
            echo $GOPATH
            pwd
            ls

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - test

